name: quick_sell
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.10.8
  share_plus: ^7.2.2
  shared_preferences: ^2.2.3
  http: ^1.2.1
  provider: ^6.1.5
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.3
  font_awesome_flutter: 10.8.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.2.0
  flutter_pdfview: ^1.3.2
  cupertino_icons: ^1.0.8
  flutter_jailbreak_detection: ^1.10.0
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.1
  uuid: ^4.3.3
  image: ^4.1.7

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/languages/en.json
    - assets/languages/ar.json
    - assets/images/
    - assets/images/logo.png
    - assets/images/logo_noBG2.png
    - assets/images/logo_noBG.jpg
    - assets/images/salesIcon.png
    - assets/images/expenseIcon.png
    - assets/images/animatedLogo.gif
    - assets/fonts/

  fonts:
    - family: NotoSansUI
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf

    - family: Arial
      fonts:
        - asset: assets/fonts/Arial.ttf
